#spring.datasource.url=jdbc:mysql://tempdb.cncmopyd0pfr.ap-northeast-2.rds.amazonaws.com:3306/speacher?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#spring.datasource.username=root
#spring.datasource.password=991021
#spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring:
  profiles:
    active: local
  h2:
    console.enabled: true
  datasource:

    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  date:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



logging.level:
  org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
cloud:
  aws:
    s3:
      bucket: lawkick
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}
